const genres = [
    "Action",
    "Adventure",
    "Alien",
    "Animation",
    "Animation-Action",
    "Animation-Adventure",
    "Animation-Comedy",
    "Animation-Cult",
    "Animation-Cyberpunk",
    "Animation-Drama",
    "Animation-Ecchi",
    "Animation-Family",
    "Animation-Fantasy",
    "Animation-Harem",
    "Animation-Historical",
    "Animation-Horror",
    "Animation-Idol",
    "Animation-Magic",
    "Animation-Mecha",
    "Animation-Military",
    "Animation-Mockumentary",
    "Animation-Movie",
    "Animation-Music",
    "Animation-Mystery",
    "Animation-Parody",
    "Animation-Post-Apocalyptic",
    "Animation-Psychological",
    "Animation-Romance",
    "Animation-Samurai",
    "Animation-School",
    "Animation-Sci-Fi",
    "Animation-Slice of Life",
    "Animation-Space",
    "Animation-Sports",
    "Animation-Superhero",
    "Animation-Supernatural",
    "Animation-Thriller",
    "Animation-Time Travel",
    "Animation-Vampire",
    "Animation-War",
    "Animation-Western",
    "Animation-Zombie",
    "Anime-Action",
    "Anime-Adventure",
    "Anime-Comedy",
    "Anime-Cult",
    "Anime-Cyberpunk",
    "Anime-Demons",
    "Anime-Drama",
    "Anime-Ecchi",
    "Anime-Fantasy",
    "Anime-Harem",
    "Anime-Historical",
    "Anime-Horror",
    "Anime-Idol",
    "Anime-Magic",
    "Anime-Mecha",
    "Anime-Military",
    "Anime-Movie",
    "Anime-Music",
    "Anime-Mystery",
    "Anime-Parody",
    "Anime-Post-Apocalyptic",
    "Anime-Psychological",
    "Anime-Romance",
    "Anime-Samurai",
    "Anime-School",
    "Anime-Sci-Fi",
    "Anime-Slice of Life",
    "Anime-Space",
    "Anime-Sports",
    "Anime-Superhero",
    "Anime-Supernatural",
    "Anime-Thriller",
    "Anime-Time Travel",
    "Anime-Vampire",
    "Anime-War",
    "Anime-Western",
    "Anime-Zombie",
    "B-Movie",
    "Biography",
    "Coming of Age",
    "Crime",
    "Cult",
    "Cyberpunk",
    "Documentary",
    "Drama",
    "Dystopian",
    "Ecchi",
    "Experimental",
    "Family",
    "Fantasy",
    "Film-Noir",
    "Found Footage",
    "Gangster",
    "Game",
    "Gender Bender",
    "Harem",
    "Heist",
    "Historical",
    "Horror",
    "Idol",
    "Magic",
    "Martial Arts",
    "Mecha",
    "Military",
    "Mockumentary",
    "Movie",
    "Music",
    "Mystery",
    "Parody",
    "Post-Apocalyptic",
    "Psychological",
    "Romance",
    "Samurai",
    "School",
    "Sci-Fi",
    "Science Fiction",
    "Silent",
    "Slice of Life",
    "Slasher",
    "Space",
    "Space Opera",
    "Sports",
    "Spy",
    "Steampunk",
    "Superhero",
    "Superpower",
    "Supernatural",
    "Teen",
    "Thriller",
    "Time Loop",
    "Time Travel",
    "Urban Fantasy",
    "Vampire",
    "War",
    "Western",
    "Western-Comedy",
    "Werewolf",
    "Zombie",
  ];
  

module.exports = genres;
